CREATE TABLE `JOB_TITLE` (
  `JOB_TITLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(45) NOT NULL,
  PRIMARY KEY (`JOB_TITLE_ID`),
  UNIQUE KEY `UNQ_JOB_DESCRIPTION` (`DESCRIPTION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

CREATE TABLE `DEPARTMENT` (
  `DEPARTMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MANAGER_ID` int(11) DEFAULT NULL,
  `NAME` varchar(45) NOT NULL,
  `PARENT_DEPARTMENT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`DEPARTMENT_ID`),
  UNIQUE KEY `UNQ_DEPT_NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

CREATE TABLE `EMPLOYEE` (
  `EMPLOYEE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(20) NOT NULL,
  `LAST_NAME` varchar(45) NOT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `SKYPE_NAME` varchar(100) DEFAULT NULL,
  `JOB_TITLE_ID` int(11) DEFAULT NULL,
  `IS_MANAGER` bit(1) NOT NULL DEFAULT b'0',
  `MANAGER_ID` int(11) DEFAULT NULL,
  `DEPARTMENT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`),
  UNIQUE KEY `UNQ_EMP_EMAIL` (`EMAIL`),
  UNIQUE KEY `UNQ_EMP_SKYPE_NAME` (`SKYPE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

ALTER TABLE DEPARTMENT ADD CONSTRAINT `FK_DEPT_PDEPT` FOREIGN KEY
(
   `PARENT_DEPARTMENT_ID`
)
REFERENCES `DEPARTMENT` (`DEPARTMENT_ID`)
;
ALTER TABLE DEPARTMENT ADD CONSTRAINT `FK_DEPT_EMPID` FOREIGN KEY
(
   `MANAGER_ID`
)
REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`)
;
ALTER TABLE EMPLOYEE ADD CONSTRAINT `FK_EMP_MGR` FOREIGN KEY
(
   `MANAGER_ID`
)
REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`)
;
ALTER TABLE EMPLOYEE ADD CONSTRAINT `FK_EMP_DPT` FOREIGN KEY
(
   `DEPARTMENT_ID`
)
REFERENCES `DEPARTMENT` (`DEPARTMENT_ID`)
;
ALTER TABLE EMPLOYEE ADD CONSTRAINT `FK_EMP_JOB` FOREIGN KEY
(
   `JOB_TITLE_ID`
)
REFERENCES `JOB_TITLE` (`JOB_TITLE_ID`)
;
INSERT INTO JOB_TITLE
(JOB_TITLE_ID,DESCRIPTION     ) VALUES
(1           ,'VICE PRESIDENT')
;
INSERT INTO EMPLOYEE
(EMPLOYEE_ID,JOB_TITLE_ID,MANAGER_ID,DEPARTMENT_ID,FIRST_NAME,LAST_NAME,EMAIL                         ,SKYPE_NAME            ,IS_MANAGER) VALUES
(1          ,1           ,NULL      ,NULL         ,'COLIN'   ,'CHAPMAN','CCHAPMAN@SYSTEMSINMOTION.COM','COLIN.CHAPMAN.SIM.AA',1         )
;
INSERT INTO DEPARTMENT
(DEPARTMENT_ID,MANAGER_ID,NAME      ,PARENT_DEPARTMENT_ID) VALUES
(1            ,1         ,'DELIVERY',NULL                )
;
UPDATE EMPLOYEE SET DEPARTMENT_ID=1
WHERE EMPLOYEE_ID=1
;

